<#
.SYNOPSIS
  Builds the installer: artifacts\setup\PodGate-<VERSION>.msi

.DESCRIPTION
  Publishes the service and the app self-contained into one folder (they share the runtime files, so the
  runtime ships once), writes the file list for the MSI, and builds it with the WiX toolset.
  Needs the .NET 10 SDK and WiX 5:

      dotnet tool install --global wix --version 5.0.2
      wix extension add -g WixToolset.Util.wixext/5.0.2
      wix extension add -g WixToolset.UI.wixext/5.0.2
#>
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$version = (Get-Content (Join-Path $root 'VERSION') -Raw).Trim()
$publish = Join-Path $root 'artifacts\publish\PodGate'
$setup = Join-Path $root 'artifacts\setup'

if (Test-Path $publish) { Remove-Item $publish -Recurse -Force }
New-Item -ItemType Directory -Force -Path $setup | Out-Null

foreach ($project in 'src\PodGate.Service\PodGate.Service.csproj', 'src\PodGate.App\PodGate.App.csproj') {
    & dotnet publish (Join-Path $root $project) -c Release -p:PublishSingleFile=false -o $publish --nologo -v quiet
    if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed: $project" }
}

# One component per file, so every file is uninstalled again. The two executables are left out: they have
# components of their own in PodGate.wxs (Windows takes the service's path from its component, and the
# installer starts the tray app by file reference).
$named = 'PodGate.Service.exe', 'PodGate.exe'
$files = Get-ChildItem $publish -Recurse -File | Where-Object { $named -notcontains $_.Name }
$components = foreach ($file in $files) {
    $relative = $file.FullName.Substring($publish.Length + 1)
    $id = 'f_' + ($relative -replace '[^A-Za-z0-9_]', '_')
    "      <Component Id=`"$id`" Bitness=`"always64`"><File Id=`"$id`_f`" Source=`"`$(PublishDir)\$relative`" KeyPath=`"yes`" /></Component>"
}

@(
    '<?xml version="1.0" encoding="utf-8"?>'
    '<!-- Generated by build.ps1 from the publish output; do not edit. -->'
    '<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">'
    '  <Fragment>'
    '    <ComponentGroup Id="PublishedFiles" Directory="INSTALLFOLDER">'
    $components
    '    </ComponentGroup>'
    '  </Fragment>'
    '</Wix>'
) | Set-Content -Path (Join-Path $setup 'Files.wxs') -Encoding utf8

$wixCommand = Get-Command wix -ErrorAction SilentlyContinue
$wix = if ($wixCommand) { $wixCommand.Source } else { Join-Path $env:USERPROFILE '.dotnet\tools\wix.exe' }
if (-not (Test-Path $wix)) { throw 'WiX not found. Install it: dotnet tool install --global wix --version 5.0.2' }

$msi = Join-Path $setup "PodGate-$version.msi"
& $wix build (Join-Path $root 'setup\PodGate.wxs') (Join-Path $setup 'Files.wxs') `
    -d Version=$version -d PublishDir=$publish `
    -ext WixToolset.Util.wixext -ext WixToolset.UI.wixext -arch x64 -o $msi
if ($LASTEXITCODE -ne 0) { throw 'wix build failed' }

Write-Host "Built $msi"
